// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace RetailCompanyProject.Migrations
{
    [DbContext(typeof(MvcLaptopContext))]
    [Migration("20210827115058_v001")]
    partial class v001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RetailCompanyProject.Models.Laptop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Screen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Laptop");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Grey",
                            ImageURL = "lenovo.jpg",
                            Name = "Lenevo",
                            Price = 3510m,
                            Quantity = 30,
                            Screen = "13 inch"
                        },
                        new
                        {
                            Id = 2,
                            Color = "Natural Silver",
                            ImageURL = "hp.png",
                            Name = "HP",
                            Price = 4100m,
                            Quantity = 40,
                            Screen = "14 inch"
                        },
                        new
                        {
                            Id = 3,
                            Color = "S.Grey",
                            ImageURL = "MacBook.jpeg",
                            Name = "Apple MacBook Air 2020",
                            Price = 4899m,
                            Quantity = 50,
                            Screen = "13 inch"
                        },
                        new
                        {
                            Id = 4,
                            Color = "Silver",
                            ImageURL = "asus.jpeg",
                            Name = "Asus X415",
                            Price = 2399m,
                            Quantity = 25,
                            Screen = "14 inch"
                        },
                        new
                        {
                            Id = 5,
                            Color = "Silver",
                            ImageURL = "dell.jpeg",
                            Name = "Dell XPS",
                            Price = 5759m,
                            Quantity = 10,
                            Screen = "13 inch"
                        });
                });

            modelBuilder.Entity("RetailCompanyProject.Models.Orders", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LaptopId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Payment_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
